### ISSUE TITLE
Upload speed is incorrect

### ISSUE THREAD

**Issue by martinbrose** [martinbrose/cloudflarepycli#18]
Hi @tevslin,

unfortunately, the upload speed is incorrect when using cloudflarepycli.

This behaviour started on 21st of May:
![Screenshot 2024-05-23 at 17 20 33](https://github.com/tevslin/cloudflarepycli/assets/13284268/ad81c51f-74cd-46c8-8a4c-73aa4b608680)

I have run the Python package myself and could replicate the strange upload measurements:
![Screenshot 2024-05-23 at 17 22 16](https://github.com/tevslin/cloudflarepycli/assets/13284268/f9c7feb7-6703-4538-a208-ca4cbb227354)

But when I run the speedtest on the Cloudflare-Website, everything seems fine:
![Screenshot 2024-05-23 at 17 24 31](https://github.com/tevslin/cloudflarepycli/assets/13284268/520288d8-7352-456a-aa7a-60856ab18627)

There might have been a change to the servertimes we use in the calculation in lines 212-213 of cloudflareclass.py.

**Comment by martinbrose** [comment]
On second thought... I didn't check the data returned from cloudflare. They probably just changed the structure. And only the test[i] references need to be updated to reflect that?

**Comment by Nytelife26** [comment]
when the error catching is stripped out of the upload test function, I observed that the upload test connections get terminated. however, the endpoint requested by cloudflare's website and their JS speedtest library remains the same. it is possible that some extra headers are now required, but I will spend some time investigating the issue.

**Comment by tevslin** [comment]
Thank you.

**Comment by Nytelife26** [comment]
it turns out fixing this issue is trivial. i merely had to replace `http://` with `https://` for all the cloudflare endpoint URLs, and I stopped receiving the errors.

before:
```
100kB_download_mbps: 7.19
1MB_download_mbps: 33.09
10MB_download_mbps: 91.75
25MB_download_mbps: 95.84
90th_percentile_down_speed: 106.99
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 399, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1076, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.11/http/client.py", line 998, in send
    self.sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```

after:
```
100kB_download_mbps: 33.2
1MB_download_mbps: 82.19
10MB_download_mbps: 93.3
25MB_download_mbps: 90.59
90th_percentile_down_speed: 96.32
100kB_upload_mbps: 21.1
1MB_upload_mbps: 24.05
10MB_upload_mbps: 26.28
90th_percentile_up_speed: 26.22
```

i have put some general work into refactoring the application as it stands, and i can open a pull request that simply fixes this issue if you like, or i can open a pull request for the whole refactoring effort. it's up to you, @tevslin.

**Comment by tevslin** [comment]
I would be happy for you to do a pr for the whole refactoring. I haven’t had time to work on this since I’ve been absorbed in an AI project so great to have your help. Thank you.
