### ISSUE TITLE
Problem with KeyError: 'region' on cfspeedtest

### ISSUE THREAD

**Issue by MrSaeid007** [martinbrose/cloudflarepycli#27]
Hello guys, I am getting this error on my server. Can you help?

root@Iranserver:~# cfspeedtest
Traceback (most recent call last):
  File "/usr/local/bin/cfspeedtest", line 8, in <module>
    sys.exit(cfspeedtest())
  File "/usr/local/lib/python3.10/dist-packages/cfspeedtest/__main__.py", line 39, in cfspeedtest
    results = CloudflareSpeedtest().run_all(megabits=not args.bps)
  File "/usr/local/lib/python3.10/dist-packages/cfspeedtest/cloudflare.py", line 212, in run_all
    meta = self.metadata()
  File "/usr/local/lib/python3.10/dist-packages/cfspeedtest/cloudflare.py", line 175, in metadata
    result_data["region"],
KeyError: 'region'

root@Iranserver:~# python3 --version
Python 3.10.12

root@IranServer:~# pip3 --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

root@IranServer:~# cfspeedtest  --debug
Starting new HTTPS connection (1): speed.cloudflare.com:443
send: b'GET /meta HTTP/1.1\r\nHost: speed.cloudflare.com\r\nUser-Agent: python-requests/2.32                                                         .3\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Tue, 13 Aug 2024 17:30:28 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Access-Control-Allow-Origin: *
header: access-control-allow-credentials: true
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=kyNupp                                                         uFXfFxktgSHhtnxykF%2FeZybgdfNwCl7bk9xtY%2B5ZsQsmgIpMdHv1J51LuZDZA2g6noj7b%2FrNa6QT6BeSF%2FVx                                                         0jQDLlQaJtXihOnisO8p2hA1p6kSTq67RttDuW9476ZL4XJ4jNrqluaVXYw4JS"}],"group":"cf-nel","max_age"                                                         :604800}
header: NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
header: Vary: Accept-Encoding
header: Server-Timing: cfRequestDuration;dur=29.999971
header: Server: cloudflare
header: CF-RAY: 8b2a6ee94b2c09af-ARN
header: Content-Encoding: gzip
header: server-timing: cfL4;desc="?proto=TCP&rtt=110362&sent=8&recv=8&lost=0&retrans=3&sent_                                                         bytes=5786&recv_bytes=774&delivery_rate=10730&cwnd=38&unsent_bytes=0&cid=58ad46ab0f1bb7a5&ts                                                         =821&x=0"
https://speed.cloudflare.com:443 "GET /meta HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/local/bin/cfspeedtest", line 8, in <module>
    sys.exit(cfspeedtest())
  File "/usr/local/lib/python3.10/dist-packages/cfspeedtest/__main__.py", line 39, in cfspee                                                         dtest
    results = CloudflareSpeedtest().run_all(megabits=not args.bps)
  File "/usr/local/lib/python3.10/dist-packages/cfspeedtest/cloudflare.py", line 212, in run                                                         _all
    meta = self.metadata()
  File "/usr/local/lib/python3.10/dist-packages/cfspeedtest/cloudflare.py", line 175, in met                                                         adata
    result_data["region"],
KeyError: 'region'

**Comment by MrSaeid007** [comment]
Hi @tevslin @Nytelife26 @martinbrose 

I fixed this error after modifying/usr/local/lib/python3.10/dist-packages/cfspeedtest/cloudflare.py with the specific below line:

    def metadata(self) -> TestMetadata:
        """Retrieve test location code, IP address, ISP, city, and region."""
        result_data: dict[str, str] = self.request_sess.get(
            "https://speed.cloudflare.com/meta"
        ).json()
        return TestMetadata(
            result_data.get("clientIp", ""),
            result_data.get("asOrganization", ""),
            result_data.get("colo", ""),
            result_data.get("country", ""),  # Use 'country' if 'region' is missing
            result_data.get("country", "")   # Use 'country' as a fallback for 'city'
       )

And its worked. The KeyError: 'region' occurs because the region key is missing in the response. I did update the metadata method to handle the absence of this key. I request you to update it in the code.

**Comment by Nytelife26** [comment]
> The `KeyError: 'region'` occurs because the region key is missing in the response. I did update the metadata method to handle the absence of this key. I request you to update it in the code.

i was not aware this could happen, honestly. would you mind letting me know where in the world this issue occurs for? i have never been made aware of an instance where the region key is missing prior to this.

**Comment by MrSaeid007** [comment]
> > The `KeyError: 'region'` occurs because the region key is missing in the response. I did update the metadata method to handle the absence of this key. I request you to update it in the code.
> 
> i was not aware this could happen, honestly. would you mind letting me know where in the world this issue occurs for? i have never been made aware of an instance where the region key is missing prior to this.

Hi @Nytelife26 

This problem happened for Iran IPs that I tested who try to use the script.
I'm not sure how many countries could be effected. but on my Germany server I don't have this problem.

I created a check_response.py script as below:

import requests

response = requests.get("https://speed.cloudflare.com/meta")
print(response.json())

Then I ran it and I get this information(JSON Response):

{
    'hostname': 'speed.cloudflare.com',
    'clientIp': '5.201.162.2',
    'httpProtocol': 'HTTP/1.1',
    'asn': 50810,
    'asOrganization': 'Mobin Net Communication Company (Private Joint Sto',
    'colo': 'ARN',
    'country': 'IR',
    'latitude': '35.69800',
    'longitude': '51.41150'
}

 It seems that the region key is missing in the JSON response. So it better that you update the script.

**Comment by tigeryfan** [comment]
I'm having this problem too.

**Comment by tigeryfan** [comment]
I'm debugging and will submit PR when fixed

**Comment by MrSaeid007** [comment]
> I'm debugging and will submit PR when fixed

Hi. it's something about ("country", "") When I changed to country its worked. 

def metadata(self) -> TestMetadata:
    """Retrieve test location code, IP address, ISP, city, and region."""
    result_data: dict[str, str] = self.request_sess.get(
        "https://speed.cloudflare.com/meta"
    ).json()
    return TestMetadata(
        result_data.get("clientIp", ""),
        result_data.get("asOrganization", ""),
        result_data.get("colo", ""),
        result_data.get("country", ""),  # Use 'country' if 'region' is missing
        result_data.get("country", "")   # Use 'country' as a fallback for 'city'
    )

Please fix this issue team @tevslin @Nytelife26 @martinbrose

**Comment by martinbrose** [comment]
Hi @MrSaeid007 and @Nytelife26,

thanks for raising this issue and proposing a change.
Sorry for my late response, I wasn't paying enough attention to the GitHub. Work was too busy.

I'll have a look this evening and will issue an update.

Cheers

**Comment by Nytelife26** [comment]
> I'm having this problem too.

can you confirm if this is also from an Iranian location, or is this another location they don't provide region data for?

**Comment by Nytelife26** [comment]
> Sorry for my late response, I wasn't paying enough attention to the GitHub. Work was too busy.

welcome back. i hope you've been keeping well :) there's a few PRs ready and waiting, but this one is safe to resolve independently of the others and without worrying about merge conflicts.

**Comment by MrSaeid007** [comment]
> > I'm having this problem too.
> 
> can you confirm if this is also from an Iranian location, or is this another location they don't provide region data for?

Dear @Nytelife26  There are two scenarios in this case.

1. Maybe there was something changed on the Cloudflare end. especially about the **region** 
2. The second case may be related to sanctions or something like that:

![photo14551248458](https://github.com/user-attachments/assets/86b1d335-2413-4f26-9770-6341ae79afd9)

However, when I edited the **region** to the **country** manually in the script file(/usr/local/lib/python3.10/dist-packages/cfspeedtest/cloudflare.py), the issue was resolved. 

BTW, thanks for @tigeryfan to send a PR request https://github.com/martinbrose/cloudflarepycli/pull/28 (Fix #27 #28) and I waiting for @martinbrose to update the code.

**Comment by Nytelife26** [comment]
based on your previous response, the region and city keys seem to be the only ones missing - if that is the case, those are the only ones we should mark as optional for now.

**Comment by martinbrose** [comment]
@Nytelife26, kind of agree with you to keep changes to the minimum.
But I'm also wondering if any of the metadata should make this fail with a KeyError in the first place.  Maybe we should change it for all of the metadata?
Am I overlooking a reason to just restrict it to region and city?

**Comment by Nytelife26** [comment]
> But I'm also wondering if any of the metadata should make this fail with a KeyError in the first place.  Maybe we should change it for all of the metadata?

My thinking was that I would rather have it be immediately obvious that something has gone wrong than have it fail silently, but I suppose you're right, metadata shouldn't impact the tests, and we don't want the program to stop working if cloudflare changes anything about the metadata either.

With that, we could have it show some kind of warning, or we could just let it return `None` for any of those values in peace. That's up to you, I think.

**Comment by martinbrose** [comment]
> My thinking was that I would rather have it be immediately obvious that something has gone wrong than have it fail silently,

Very valid point. A speed result of zero should probably always indicate that the connection has a problem and shouldn't be the result of the speed test itself failing. Would it always fail somewhere else in our code? I need to think about that.

**Comment by tigeryfan** [comment]
In my testing, returning `None` for `region` does not stop the speedtest from functioning correctly. I'll still have to test if `country` works better. Thanks for the suggestion!

**Comment by Nytelife26** [comment]
> A speed result of zero should probably always indicate that the connection has a problem and shouldn't be the result of the speed test itself failing. Would it always fail somewhere else in our code? I need to think about that.

In the specific scenario where the connection has a problem, it should fail when the requests are made. If something else goes wrong and the server timings report as zero, it will fail when it attempts to divide by those timings for upload tests.

Internal error handling is currently, as with the original cfspeedtest implementation, rather minimal. I believe this is the best approach for allowing external callers (like the CLI itself) to handle errors in the most appropriate way for each use case.

I am ultimately unsure whether it would be better to guard internally against future changes, or design the library to reflect the current state of the API and have it error out if the data appears to be incorrect.

It would be rather lovely if Cloudflare standardised and publicised this API, like Ookla's, but we can always make do. Their own library hasn't changed in over a year, so their implementation would provide a good reference for what kind of data inconsistencies we can expect, and I believe we should follow those instead of creating blanket protections for all possible missing metadata.

**Comment by martinbrose** [comment]
Yes, thinking the same currently. Better to know that something is wrong with the metadata.

@tigeryfan could you please perform the changes just for `region` and `country`?
Please also change `TestMetadata` as mentioned by @Nytelife26 .

Happy to merge your PR right after.

**Comment by martinbrose** [comment]
And on that sanctions point mentioned by @MrSaeid007 . I believe there would be better ways to implement sanctions on Cloudflare side. Hence, my working assumption is that this is a bug.

**Comment by Nytelife26** [comment]
You may find it interesting to note that cloudflare's library for its speedtest API doesn't seem to include metadata retrieval at all. The closest it has is a reachability check, so this is an area where we're ahead.

Maybe the metadata retrieval should be optional altogether?

**Comment by tigeryfan** [comment]
> please perform the changes just for region and country

I'll do this later today

**Comment by tigeryfan** [comment]
> Maybe the metadata retrieval should be optional altogether?

I'll test this too.
